from rest_framework import serializers

from .models import Book, Category


class CategorySerializer(serializers.ModelSerializer):
    """Convert Category objects to and from API-friendly data."""

    class Meta:
        model = Category
        fields = ["id", "name", "slug", "description", "created_at"]        # Define which model fields are exposed through the API.
        read_only_fields = ["id", "created_at"]                             # These fields are generated by the database/application. Clients can read them but should not provide them.


class BookSerializer(serializers.ModelSerializer):
    """Convert Book objects to and from API-friendly data."""

    class Meta:
        model = Book
        fields = [
            "id",
            "category",
            "name",
            "slug",
            "author",
            "isbn",
            "publisher",
            "publication_date",
            "description",
            "price",
            "stock",
            "image",
            "is_active",
            "created_at",
            "updated_at",
        ]
        read_only_fields = ["id", "created_at", "updated_at"]
